// Generator sprite'ów box-shadow z map ASCII (piksel = 4px).
// Użycie: node scripts/genPixelArt.mjs  → CSS na stdout, do wklejenia w globals.css.
const PX = 4;
const KOLORY = {
  H: 'var(--czern)', // włosy / buty
  S: '#f2c094', // skóra
  Y: 'var(--zolty)', // koszulka
  W: 'var(--bialy)', // spodenki
};

const FRAMES = {
  'pixel-player .frame-a': `
...HH.....
..HHHH....
..SSSS....
..SSSS....
...YY.....
..YYYY....
.SYYYYS...
.SYYYYS...
..YYYY....
..WWWW....
..WWWW....
..SS.SS...
..SS.SS...
..SS.SS...
..SS.SS...
.HHH.HHH..
`,
  'pixel-player .frame-b': `
...HH.....
..HHHH....
..SSSS....
..SSSS....
...YY.....
..YYYY....
.SYYYYS...
.SYYYYS...
..YYYY....
..WWWW....
..WWWW....
.SS..SS...
.SS..SS...
.S....SS..
.S....SS..
HHH....HHH
`,
  'pixel-player .frame-kick': `
...HH.....
..HHHH....
..SSSS....
..SSSS....
...YY.....
..YYYY....
.SYYYYS...
.SYYYYS...
..YYYY....
..WWWW....
..WWWW....
..SS......
..SS..SS..
..SS...SSH
..SS......
.HHH......
`,
};

for (const [nazwa, mapa] of Object.entries(FRAMES)) {
  const wiersze = mapa.trim().split('\n');
  const shadows = [];
  wiersze.forEach((wiersz, y) => {
    [...wiersz].forEach((znak, x) => {
      const kolor = KOLORY[znak];
      if (kolor) shadows.push(`${x * PX}px ${y * PX}px ${kolor}`);
    });
  });
  console.log(`.${nazwa} {\n  box-shadow:\n    ${shadows.join(', ')};\n}\n`);
}
